language: python
python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE=cloto_settings.settings_tests

script:
  - ls
  - cd fiware_cloto
  - python fiware-pep8.py .
  - sudo ./build.sh travis_build

after_success:
  - coveralls
