language: python
python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE=fiware_cloto.cloto_settings.settings_tests
    - COVERALLS_SERVICE_NAME=travis-ci
    # COVERALLS_REPO_TOKEN (encrypted)
    - secure: now6MbagvDOG5SieEoAjCrO0XRXMJsf0u

script:
  - sh checkstyle.sh
  - sudo ./build.sh travis_build

after_success:
  - coveralls
